In [1]:
import pandas as pd

d_train = pd.read_csv('/home/k.p.osminin/external_hdfs/la_tcs_ha_train.csv', index_col = 0)

d_train.head()

IOError: File /home/k.p.osminin/external_hdfs/la_tcs_ha_train.csv does not exist

In [ ]:
import os
os.getcwd()

In [8]:
sum(d_train['label'])/len(d)

0.00058113447357987277

In [9]:
d_test = pd.read_csv('/home/k.p.osminin/external_hdfs/la_tcs_ha_test.csv', index_col = 0)

d_test.head()

label  first_day   tcs_maxs  hash_score
0      0          0  -9.298911    0.004665
1      0          0 -12.595378    0.002222
2      0          0  -9.298911    0.004008
3      0          0 -12.392008    0.002244
4      0          0 -13.785701    0.002222

In [11]:
sum(d_test['label'])/len(d)/(sum(d_train['label'])/len(d))

1.3297235023041474

In [12]:
from sklearn.metrics import roc_auc_score

roc_auc_score(d_test['label'], d_test['tcs_maxs'])

0.85258024432714097

In [13]:
roc_auc_score(d_test['label'], d_test['hash_score'])

0.82788427288479427

In [16]:
from numpy import corrcoef

corrcoef((d_test['label'], d_test['tcs_maxs'], d_test['hash_score']))

array([[ 1.        ,  0.03593242,  0.1039207 ],
       [ 0.03593242,  1.        ,  0.24375032],
       [ 0.1039207 ,  0.24375032,  1.        ]])

In [17]:
corrcoef(d_test['label'], d_test['tcs_maxs'])

array([[ 1.        ,  0.03593242],
       [ 0.03593242,  1.        ]])

In [18]:
corrcoef(d_test['label'], d_test['tcs_maxs'])

array([[ 1.        , -0.03593242],
       [-0.03593242,  1.        ]])

In [24]:
X_train = d_train.iloc[:,1:]
y_train = d_train['label']

X_test = d_test.iloc[:,1:]
y_test = d_test['label']

In [25]:
from sklearn.ensemble import AdaBoostClassifier

cl = AdaBoostClassifier()
cl.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [27]:
roc_auc_score(y_test, cl.predict_proba(X_test)[:,1])

0.9117480702763695

In [3]:
print('{0} AUCROC train: {1:.6f}. test: {2:.6f}'.format(
               'AdaBoost',
                roc_auc_score(
                  y_true = y_train, 
                  y_score = cl.predict_proba(X_train)[:,1]
                ),
                roc_auc_score(
                  y_true = y_test, 
                  y_score =  cl.predict_proba(X_test)[:,1]
                ),
))



NameError: name 'roc_auc_score' is not defined